### ISSUE TITLE
Notebook on lowest common ancestor algorithm

### ISSUE THREAD

**Issue by dtekinoglu** [networkx/nx-guides#66]
Hello, 

I want to create an explanatory notebook on lowest common ancestor algorithm. If it is okay for you, I will start working on it.

**Comment by rossbar** [comment]
I think LCA would be a good candidate for a notebook; however, there are a few things to be aware of...
 - The implementation is quite complicated. This of course makes it a good candidate for a detailed explanation, but it *also* makes it a good candidate for review. Perhaps the best way to explain the LCA algorithm would be to see if we can't make the code itself more clear!
 - Similarly, there is at least one open issue on LCA which illustrates a corner-case that no one has yet been able to track down: networkx/networkx#4458 and the related examples in networkx/networkx#4844. It's a completely different project than creating the notebook, but tracking down and fixing this case would be a huge improvement to the LCA function. I just wanted to mention it since you're interested in LCA!

**Comment by dtekinoglu** [comment]
Thank you @rossbar , I will be looking into it.
